---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
  labels:
    app: 5gcore
  name: 5gcore-subscription-1
  namespace: open5gcore
spec:
  channel: open5gcore/cnvopen5gcore
  name: 5gcore
  packageOverrides:
  - packageName: 5gcore
    packageAlias: 5gcore
  packageFilter:
    version: "0.0.1"
  placement:
    placementRef:
      kind: PlacementRule
      name: 5gcore-placement-1
