---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: Release-1.0
    apps.open-cluster-management.io/git-path: 5gcore
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: 5gcore
  name: 5gcore-subscription-1
  namespace: open5gcore
spec:
  channel: open5gcore/cnvopen5gcore
  placement:
    placementRef:
      kind: PlacementRule
      name: 5gcore-placement-1
