apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cluster-sno02-atx-kskels-com
  namespace: ztp-clusters
spec:
  clusterConditions:
    - type: "ManagedClusterJoined"
      status: "True"
  clusterSelector:
    matchExpressions: []
    matchLabels:
      low-latency: "true"
