apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: cluster-sno02-atx-kskels-com-subscription
  namespace: ztp-clusters
  labels:
    app: cluster-sno02-atx-kskels-com-configs
  annotations:
    apps.open-cluster-management.io/git-path: configs/sno02.atx.kskels.com/
    apps.open-cluster-management.io/git-branch: main
spec:
  channel: ztp-clusters/ztp-repository
  placement:
    placementRef:
      kind: PlacementRule
      name: cluster-sno02-atx-kskels-com
