apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: cluster-sno02-atx-kskels-com-configs
  namespace: ztp-clusters
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - cluster-sno02-atx-kskels-com-configs
