apiVersion: extensions.hive.openshift.io/v1beta1
kind: AgentClusterInstall
metadata:
  name: ocp01-atx-kskels-com
  namespace: ocp01-atx-kskels-com
  annotations:
    agent-install.openshift.io/install-config-overrides: '{"networking":{"networkType":"OVNKubernetes"}}'
spec:
  clusterDeploymentRef:
    name: ocp01-atx-kskels-com
  imageSetRef:
    name: openshift-v4.10.22
  networking:
    clusterNetwork:
      - cidr: "10.94.0.0/16"
        hostPrefix: 23
    serviceNetwork:
      - "172.95.0.0/16"
    #machineNetwork:
    #  - cidr: "192.168.212.0/24"
  apiVIP: 192.168.212.24
  ingressVIP: 192.168.212.25
  provisionRequirements:
    controlPlaneAgents: 3
    workerAgents: 0
  sshPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGxLsmU7suROe520RAqaqE+Xtmx0iIGpG0IFLKcduA3t kskels@redhat.com"
