apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: ocp01-atx-kskels-com
  namespace: ocp01-atx-kskels-com
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  clusterRef:
    name: ocp01-atx-kskels-com
    namespace: ocp01-atx-kskels-com
  sshAuthorizedKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDst3pB7hKcKLvq2P7vON4OKgUZDInk9zEu/Kz2ruh/D kskels@redhat.com'
  agentLabelSelector:
    matchLabels:
      cluster-name: ocp01
  pullSecretRef:
    name: pull-secret
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: ocp01
