---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
  labels:
    app: 5gran
  name: 5gran-subscription-2
  namespace: open5gran
spec:
  channel: open5gran/cnvopen5gcore
  name: 5gran
  packageOverrides:
  - packageName: 5gran
    packageAlias: 5gran
  packageFilter:
    version: "0.0.1"
  placement:
    placementRef:
      kind: PlacementRule
      name: 5gran-placement-1
