---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: Release-1.0
    apps.open-cluster-management.io/git-path: 5gran
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: 5gran
  name: 5gran-subscription-2
  namespace: open5gran
spec:
  channel: open5gran/cnvopen5gcore
  placement:
    placementRef:
      kind: PlacementRule
      name: 5gran-placement-1
