apiVersion: performance.openshift.io/v2
kind: PerformanceProfile
metadata:
  name: performance-profile
spec:
  # add pci=realloc for X710 SR-IOV BIOS workaround, see
  # https://access.redhat.com/solutions/37376
  additionalKernelArgs:
  - audit=0
  - mce=off
  - nmi_watchdog=0
  - pci=realloc
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 8
      size: 1G
  cpu:
    isolated: 0-1
    reserved: 3-4
  machineConfigPoolSelector:
    pools.operator.machineconfiguration.openshift.io/master: ""
  nodeSelector:
    node-role.kubernetes.io/master: ""
  numa:
    topologyPolicy: single-numa-node
  realTimeKernel:
    enabled: false
