apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: policy-x710-1-openshift
  namespace: openshift-sriov-network-operator
spec:
  resourceName: x710_1_openshift
  deviceType: netdevice
  isRdma: false
  linkType: eth
  mtu: 1500
  nicSelector:
    vendor: "8086"
    deviceID: "1572"
    pfNames: ["ens4f1#0-0"]
  numVfs: 9
  nodeSelector:
    node-role.kubernetes.io/master: ""
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: policy-x710-1-vfio-pci
  namespace: openshift-sriov-network-operator
spec:
  resourceName: x710_1_vfio_pci
  deviceType: vfio-pci
  isRdma: false
  linkType: eth
  mtu: 1500
  nicSelector:
    vendor: "8086"
    deviceID: "1572"
    pfNames: ["ens4f1#1-4"]
  numVfs: 9
  nodeSelector:
    node-role.kubernetes.io/master: ""
---
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: policy-x710-1-netdevice
  namespace: openshift-sriov-network-operator
spec:
  resourceName: x710_1_netdevice
  deviceType: netdevice
  isRdma: false
  linkType: eth
  mtu: 1500
  nicSelector:
    vendor: "8086"
    deviceID: "1572"
    pfNames: ["ens4f1#5-8"]
  numVfs: 9
  nodeSelector:
    node-role.kubernetes.io/master: ""
