apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: policy-x710-vfio-pci-1
  namespace: openshift-sriov-network-operator
spec:
  nodeSelector:
    node-role.kubernetes.io/master: ""
  deviceType: vfio-pci
  isRdma: false
  linkType: eth
  mtu: 1500
  nicSelector:
    vendor: "8086"
    deviceID: "1572"
    rootDevices:
      - "0000:06:00.1"
  numVfs: 4
  resourceName: x710_vfio_pci_1
