apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 5gcore
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: 5gcore-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: '5gcore-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://kskels.github.io/charts
        chart: 5gcore
        targetRevision: 0.0.1
      destination:
        server: '{{server}}'
        namespace: open5gcore
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
            - CreateNamespace=true
---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: 5gcore-placement
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          usage: edge

