apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 5gcore-argo
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: 5gcore-placement-argo
        requeueAfterSeconds: 180
  template:
    metadata:
      name: '5gcore-argo-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/kskels/cnvopen5gcore.git
        path: 5gcore
        targetRevision: Release-1.0
      destination:
        server: '{{server}}'
        namespace: open5gcore
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
            - CreateNamespace=true
---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: Placement
metadata:
  name: 5gcore-placement-argo
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          5gcore: "true"

