apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-5gcore
  namespace: ztp-clusters
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-5gcore
        spec:
          remediationAction: enforce
          severity: high
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: open5gcore
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: open5gcore-anyuid
                subjects:
                  - kind: ServiceAccount
                    name: default
                    namespace: open5gcore
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: 'system:openshift:scc:anyuid'
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: open5gcore-hostaccess
                subjects:
                  - kind: ServiceAccount
                    name: default
                    namespace: open5gcore
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: 'system:openshift:scc:hostaccess'
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: open5gcore-hostmount-anyuid
                subjects:
                  - kind: ServiceAccount
                    name: default
                    namespace: open5gcore
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: 'system:openshift:scc:hostmount-anyuid'
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: open5gcore-privileged
                subjects:
                  - kind: ServiceAccount
                    name: default
                    namespace: open5gcore
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: 'system:openshift:scc:privileged'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-5gcore
  namespace: ztp-clusters
placementRef:
  name: placement-policy-5gcore
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-5gcore
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-5gcore
  namespace: ztp-clusters
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: 5gcore
        operator: In
        values:
          - "true"
