apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: sno02-atx-kskels-com
  namespace: sno02-atx-kskels-com
  labels:
    name: "sno02"
    sno: "true"
    usage: "development"
    remote-cluster: "true"
    cloud: "all"

    # Labels for OpenShift Gitops
    cluster.open-cluster-management.io/clusterset: "all-openshift-clusters"
    vendor: "OpenShift"

spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
