apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: sno02-atx-kskels-com
  namespace: sno02-atx-kskels-com
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  clusterRef:
    name: sno02-atx-kskels-com
    namespace: sno02-atx-kskels-com
  sshAuthorizedKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGxLsmU7suROe520RAqaqE+Xtmx0iIGpG0IFLKcduA3t kskels@redhat.com'
  additionalNTPSources:
    - 192.168.2.1
  agentLabelSelector:
    matchLabels:
      cluster-name: sno02
  pullSecretRef:
    name: pull-secret
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: sno02
