---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: bmc-secret
  namespace: sno02-atx-kskels-com
stringData:
  username: admin
  password: admin
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: sno02
  namespace: sno02-atx-kskels-com
  labels:
    infraenvs.agent-install.openshift.io: "sno02-atx-kskels-com"
  annotations:
    inspect.metal3.io: disabled
    bmac.agent-install.openshift.io/hostname: "sno02"
spec:
  online: true
  bootMACAddress: 52:54:00:c2:7c:d0
  automatedCleaningMode: metadata
  rootDeviceHints:
    deviceName: "/dev/vda"
  bmc:
    # for test lab using libvirt with sushy-tools
    # https://docs.openstack.org/sushy-tools/latest/
    address: redfish-virtualmedia+http://192.168.211.5:8000/redfish/v1/Systems/846de987-0702-47f9-b0ab-f9536e74b1c5
    credentialsName: bmc-secret
    disableCertificateVerification: true
...
