apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: sno01-atx-kskels-com
  namespace: sno01-atx-kskels-com
  labels:
    cluster-name: sno01
spec:
  config:
    interfaces:
      - name: enp1s0
        type: ethernet
        state: up
        ipv4:
          enabled: true
          address:
            - ip: 192.168.212.50
              prefix-length: 24
          dhcp: false
        ipv6:
          enabled: false

      - name: enp8s0.4004
        type: vlan
        state: up
        vlan:
          base-iface: enp8s0
          id: 4004

    dns-resolver:
      config:
        search:
          - kskels.com
        server:
          - 192.168.2.1
    routes:
      config:
        - destination: 0.0.0.0/0
          next-hop-address: 192.168.212.1
          next-hop-interface: enp1s0
          table-id: 254
  interfaces:
    - name: "enp1s0"
      macAddress: "52:54:00:4e:3a:2e"
