apiVersion: agent-install.openshift.io/v1beta1
kind: InfraEnv
metadata:
  name: sno01-atx-kskels-com
  namespace: sno01-atx-kskels-com
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  clusterRef:
    name: sno01-atx-kskels-com
    namespace: sno01-atx-kskels-com
  sshAuthorizedKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQD2ySABFOLhAey0kenQr6c1Hu8Qc5YPXgYxmc2kObaE8DTYoQWFIUEVZnrwVwHuVfjUH6EUo7rUYHD+IJgsNbQ7vHR50F9+MO5qTkT2biWlhaS32wVr3f9xk6GAxTo2UxHPkzcBnXqC0Qsu6GQriz7yenMJLW6ba4tIvBf/tTKVQwuNWxAn4fA8PLhc2YOgHVYdAUHkGAfEzl5f8lCKYliMTdR9COVjm6E7rAhKFAFBJU+oUiWCVhnfLrpQpBg3oHGDy54zMj/jch8bksr1WJq52BlLhujpVHT4GrUZCbs4vjWoMQQJTovdPNALITljcfPd4GAVfwgiG4Lf8A4njX5rX4t8qkxG8n9xMr7DkNYnouUseOL/EsZ7iX3tSlPY7QF18yTQ+byc55KtDE1HsI6mnIJ1K4Egp3iH+1T8gtfI0h4cNmeBvjai/X8UrRa3GFYCEFhmYNYGGd9NMKHqMvV/7pBRIMuEDzpf7adcTOwTwwdh701ZRV1Ry+daEdiay2k= bpandey@Balkrishnas-MacBook-Pro"
  agentLabelSelector:
    matchLabels:
      cluster-name: sno01
  pullSecretRef:
    name: pull-secret
  nmStateConfigLabelSelector:
    matchLabels:
      cluster-name: sno01
